baseURL: "https://gilles13.github.io/mon-blog/"
languageCode: "fr-fr"
title: "Mon Blog"
theme: "hugo-livestyle"  # remplace par ton thème si différent
relativeURLs: true
canonifyURLs: true
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
permalinks:
  post: /:year/:month/:day/:slug/

# Paramètres personnalisés pour le thème
params:
  author: "Gilles"
  paginate: 10               # nombre d’articles par page
  enableRobotsTXT: true      # génère un robots.txt
  hasCJKLanguage: false
  description: "Bienvenue sur mon blog Hugo généré avec blogdown"
  favicon: favicon.ico
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - bash
    - r
    - yaml
  logo:
    alt: Logo
    height: 50
    url: monlogo.jpg
    width: 50

# markup
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: false

# Menu de navigation
menu:
  main:
    - identifier: home
      name: Accueil
      url: /
      weight: 1
    - identifier: about
      name: À propos
      url: /about/
      weight: 2
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 3

# Footer simple
footer:
  copyright:
    text: "© 2025 Gilles"
    url: "https://gilles13.github.io/mon-blog/"

